project:
  type: default
  output-dir: _output

format:
  html:
    toc: true
    toc-depth: 3
    theme: cosmo
    number-sections: false
    code-copy: true
  pdf:
    toc: true
    number-sections: false
    keep-tex: false
execute:
  echo: false
  warning: false
  message: false
  cache: false

metadata:
  author: MAPP Metabolomics Unit
  title: Metabolomics Analysis Draft Report
